### ISSUE TITLE
OuterConnection支持web楼台

### ISSUE THREAD

**Issue by toontong** [dantezhu/maple#1]
需要的是对外使用websocket，对内可以继续使用Box作通信。

初步看了一下代码，如果需要修改支持websocket，应该是修改或增加一个类似OuterConnection的实现就可以了吧。请问还可能会有什么坑？

对gateway+worker 双进程框架非常认同。赞一个。

**Comment by dantezhu** [comment]
谢谢。是可以的这么改的。

如果对性能没什么要求的话，最快的方式是写一个proxy server，做一下消息透传就可以了。python有很多websocket的框架。

**Comment by toontong** [comment]
请教一个问题，worker是多进程的，并且是向gateway要消息的，那么如果worker内存中是有状态的，如果确定同一个连接（用户）请求包都是被同一个worker进程消化？？
特别是如果 一个worker保持一个牌局的中途接收到kill信号要退出时，贵方做法是如何保持牌局完结才退出？

**Comment by dantezhu** [comment]
worker内存是无状态的，如果一定要改成有状态就不是这样的架构了。如果一定要这么改，基本就全改了。
